# Шаг 1: Сборка приложения
FROM node:20-alpine AS builder

# Устанавливаем зависимости (поддержка yarn, npm, pnpm)
WORKDIR /app
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
    npm install; \
    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
    elif [ -f package-lock.json ]; then npm ci; \
    elif [ -f pnpm-lock.yaml ]; then corepack enable && pnpm install --frozen-lockfile; \
    else echo "Lockfile not found." && exit 1; \
    fi

# Копируем исходный код и env-файлы
COPY . .

ENV NEXT_PUBLIC_API_URL=https://in.exporteru.com
ENV NEXT_PUBLIC_API_URL_SECOND=https://in.exporteru.com
ENV NEXT_PUBLIC_TELEPHONE=74959833888
ENV NEXT_PUBLIC_EMAIL=info@exporteru.com
ENV NEXT_PUBLIC_INSTA=info@exporteru.com
ENV NEXT_PUBLIC_TELEGRAM=made_in_russia
ENV NEXT_PUBLIC_SITE_URL=https://cn.exporteru.com
ENV INTERNAL_REQUEST_SECRET=wEEEhaveaStrosdvqUNJQreEA2819lYstRongSeCRrRRetkeyonrussiainmade8234
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_PUBLIC_RECAPTCHA_KEY=6LdOU8YrAAAAAB__8RLFwWgFcMeD_FmKBISm9hD7
ENV RECAPTCHA_SECRET_KEY=6LdOU8YrAAAAACMj5KhTh0W_8_1fhg5hKQ0OIZy9
ENV NEXT_PUBLIC_BOT_NAME=exporteruchinabot
ENV BUNNY_CDN_URL=https://exporteru.b-cdn.net
ENV BUNNY_STORAGE_ZONE=exporteru-cache
ENV NEXT_PUBLIC_CDN_FOLDER=_next_in

# Собираем приложение (с standalone)
RUN npm run build

# Шаг 2: Продакшен образ
FROM node:20-alpine AS production

WORKDIR /app

ENV NEXT_PUBLIC_API_URL=https://in.exporteru.com
ENV NEXT_PUBLIC_API_URL_SECOND=https://in.exporteru.com
ENV NEXT_PUBLIC_TELEPHONE=74959833888
ENV NEXT_PUBLIC_EMAIL=info@exporteru.com
ENV NEXT_PUBLIC_INSTA=info@exporteru.com
ENV NEXT_PUBLIC_TELEGRAM=made_in_russia
ENV NEXT_PUBLIC_SITE_URL=https://in.exporteru.com
ENV INTERNAL_REQUEST_SECRET=wEEEhaveaStrosdvqUNJQreEA2819lYstRongSeCRrRRetkeyonrussiainmade8234
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_PUBLIC_RECAPTCHA_KEY=6LdOU8YrAAAAAB__8RLFwWgFcMeD_FmKBISm9hD7
ENV RECAPTCHA_SECRET_KEY=6LdOU8YrAAAAACMj5KhTh0W_8_1fhg5hKQ0OIZy9
ENV PORT=3000
ENV NEXT_PUBLIC_BOT_NAME=exporteruchinabot
ENV BUNNY_CDN_URL=https://exporteru.b-cdn.net
ENV BUNNY_STORAGE_ZONE=exporteru-cache
ENV NEXT_PUBLIC_CDN_FOLDER=_next_in

# Копируем только необходимые файлы из builder
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# Для кастомного сервера (если используется)
# COPY --from=builder /app/server.js ./

# Оптимизация образа
RUN apk add --no-cache curl && \
    addgroup -g 1001 -S nodejs && \
    adduser -S nextjs -u 1001 -G nodejs && \
    chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=3s \
    CMD curl -f http://localhost:3000 || exit 1

CMD ["node", "server.js"]
